name: korean_particle
description: Prepositional particles in Korean for Dart
version: 1.0.2
homepage: https://github.com/Geektree0101/korean_particle
repository: https://github.com/Geektree0101/korean_particle

environment:
  sdk: '>=2.17.0 <4.0.0'
    
dev_dependencies:
  test: ^1.21.0